# Hyperland Config File


# Set Keywords / Variables

$mainMod = SUPER
$terminal = alacritty
$fileManager = dolphin
$menu = anyrun


# Sub-config files

source = ~/.config/hypr/mainMod.conf
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/audio.conf
source = ~/.config/hypr/env.conf
source = ~/.config/hypr/theme.conf
source = ~/.config/hypr/windows_workspaces.conf


# Autostart programs

exec-once = dunst

# TODO fix the clipboard.
#exec-once = clipse -listen

exec-once = swww-daemon
#exec-once = swww clear 000000
#exec-once = swww img -t any --transition-fps 60 Desktop/cyberpunk/pexels-incrediblerafa-cyber-city-walk.jpg
exec-once = swww img -t fade --transition-fps 60 Desktop/autumn/pexels-simon73-2gold-leaves-on-dark-wood.jpg


# Input

# https://wiki.hyprland.org/Configuring/Variables/#input
input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.

    touchpad {
        natural_scroll = false
    }
}

# https://wiki.hyprland.org/Configuring/Variables/#gestures
gestures {
    workspace_swipe = false
}

# Example per-device config
# See https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs for more
device {
    name = epic-mouse-v1
    sensitivity = -0.5
}
