# Monitors

# See https://wiki.hyprland.org/Configuring/Monitors/
# monitor = name, resolution, position, scale
# instead of xrandr, use `hyprctl monitors` for monitor list & details
monitor = DP-1, 3840x2160, auto, auto
#monitor = HDMI-A-1, 3840x2160, auto, auto
monitor = HDMI-A-1, disable

# For adding general monitors to right of current one at highest resolution
monitor = , highres, auto, 1
