[icons]
icons = "awesome6"

[icons.overrides]
bat = "| |"
bat_full = "|X|"
bat_charging = "|^|"
bat_discharging = "|v|"

# Internets

[[block]]
block = "net"

# Local

[[block]]
block = "custom"
command = '''echo "$(whoami) @ $(cat /etc/hostname)"'''
interval = "once"
#icons_format = "{icon}"


[[block]]
block = "custom"
command = "echo `uname` `uname -r | tr - . | cut -d. -f1-2`"
interval = "once"

[[block]]
block = "nvidia_gpu"
interval = 30

[[block]]
block = "cpu"
interval = 3

[[block]]
block = "temperature"
interval = 10
scale = "celsius"
chip = "*-isa-*"

[[block]]
block = "memory"

[[block]]
block = "time"
format = "$icon $timestamp.datetime(f:'%F %b %a %T')"


[[block]]
block = "sound"

#[[block]]
#block = "bluetooth"
